name: test for workflow
on:
  push:
    branches:
      - main

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Notes
        id: get_release_notes
        run: |
          RELEASE_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/grayankit/DantotsuRe/releases/latest")
          RELEASE_NOTES=$(echo "$RELEASE_DATA" | jq -r '.body')
          echo "Release Notes: $RELEASE_NOTES"
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Format Release Notes
        id: format_notes
        run: |
          {
            echo "🚀 **Features**"
            grep -iE '^\*\s\[[a-f0-9]+\]\(.*\):\sfeat' <<< "$RELEASE_NOTES" | head -n 5 | sed -E 's/(\*\s\[[a-f0-9]+\]\(.*\)):\s[^:]+:\s/\1 : /g' || echo "None"
            echo ""
            echo "🐛 **Fixes**"
            grep -iE '^\*\s\[[a-f0-9]+\]\(.*\):\sfix' <<< "$RELEASE_NOTES" | head -n 5 | sed -E 's/(\*\s\[[a-f0-9]+\]\(.*\)):\s[^:]+:\s/\1 : /g' || echo "None"
            echo ""
            echo "🛠 **Chores**"
            grep -iE '^\*\s\[[a-f0-9]+\]\(.*\):\schore' <<< "$RELEASE_NOTES" | head -n 5 | sed -E 's/(\*\s\[[a-f0-9]+\]\(.*\)):\s[^:]+:\s/\1 : /g' || echo "None"
            echo ""
          } > formatted_notes.txt
          cat formatted_notes.txt

      - name: Send Release Notes to Telegram
        run: |
          cat formatted_notes.txt
          FORMATTED_NOTES=$(cat formatted_notes.txt)
          echo "$FORMATTED_NOTES" > dev_info.txt
          # making the file executable
          chmod +x scripts/tel_parser.sed
          ./scripts/tel_parser.sed dev_info.txt >> output.txt
          dev_info_tel=$(< output.txt)

          telegram_dev_info="<blockquote>${dev_info_tel}</blockquote>"
          echo "$telegram_dev_info"
          
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d @<(jq -n --arg chat_id "${{ secrets.TELEGRAM_CHANNEL_ID }}" \
                          --arg thread_id "${{ secrets.TELEGRAM_THREAD_ID }}" \
                          --arg text "$FORMATTED_NOTES" \
                          '{ "chat_id": $chat_id, "message_thread_id": $thread_id, "text": $text, "parse_mode": "HTML", "disable_web_page_preview": true }')
